name: Build NuGet package

env:
  INNO_VERSION: 5.6.1

on: [push, pull_request]

jobs:
  build:
    name: Build package
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1

    - name: Download Inno Setup installer
      run: curl -L -o installer.exe http://files.jrsoftware.org/is/5/innosetup-${{ env.INNO_VERSION }}.exe

    - name: Install Inno Setup
      run: ./installer.exe /verysilent /allusers /dir=inst

    - name: List installed files
      run: gci inst -Recurse -File

    - name: Build NuGet package
      run: nuget pack Tools.InnoSetup.Ansi.nuspec -Verbosity detailed

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget-package
        path: "*.nupkg"


  publish:
    name: Publish release to NuGet
    runs-on: windows-latest
    needs: build
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package

      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-api-key-source: https://www.nuget.org/api/v2/package

      - name: Publish to NuGet
        run: nuget push *.nupkg -Source https://www.nuget.org/api/v2/package
